### PR TITLE
Fix bin/setup for dashboard

### PR DESCRIPTION
**Pull request by treydock**
This fixes a change introduced in #93.

Error I was getting:

```
Traceback (most recent call last):
	3: from ./bin/setup:36:in `<main>'
	2: from /opt/rh/rh-ruby25/root/usr/share/ruby/fileutils.rb:122:in `cd'
	1: from /opt/rh/rh-ruby25/root/usr/share/ruby/fileutils.rb:122:in `chdir'
./bin/setup:45:in `block in <main>': undefined method `sh' for main:Object (NoMethodError)
```

### CODE REVIEW

**Comment by johrstrom** [comment]
I just ran into this as well.  I'm good with this change.
