### ISSUE TITLE
popover is not a function error

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2843]
I just noticed that popovers aren't working in 3.0.1. It fails with this error - which IIRC we've seen before.

![image](https://github.com/OSC/ondemand/assets/4874123/6fb154df-d9f6-49a0-bf8a-d9b222d4a971)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204687502928382) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
I cannot now replicate this. Not quite sure what I did to get this error, but I don't see it in production or development.
